import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import express from 'express';
import path from 'node:path';
import { chromium } from 'playwright';
import { vaultRoutes } from './vaultRoutes.ts';
import { migrate, pool } from './vaultRepository.ts';

await migrate();
const app = express();
app.use(express.json()); app.use('/api/vault', vaultRoutes);
app.use(express.static(path.resolve('frontend/dist')));
const server = app.listen(0, '0.0.0.0');
await new Promise(resolve => server.once('listening', resolve));
const root = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
let testId;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage();
  const errors = [];
  await page.addInitScript(() => {
    window.__vaultNotifications = [];
    class TestNotification {
      static permission = 'granted';
      static async requestPermission() { return 'granted'; }
      constructor(title, options) { window.__vaultNotifications.push({ title, body: options.body }); }
      close() {}
    }
    window.Notification = TestNotification;
  });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(root);
  await page.getByRole('heading', { name: 'Create your first locked message' }).waitFor();
  assert.equal(await page.locator('h1').innerText(), 'Vault');
  const overflow = async () => page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  assert.equal(await overflow(), false);
  await page.getByRole('button', { name: 'New message', exact: true }).first().focus();
  await page.keyboard.press('Enter');
  await page.getByRole('dialog').waitFor();
  const note = 'BROWSER-CHECK original message\nSecond line.';
  await page.getByLabel('Title', { exact: true }).fill('Browser verification note');
  await page.getByLabel('Message', { exact: true }).fill(note);
  const future = new Date(Date.now() + 180000);
  future.setMinutes(future.getMinutes() - future.getTimezoneOffset());
  await page.getByLabel('Release date and time').fill(future.toISOString().slice(0,16));
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download recovery file' }).click();
  const download = await downloaded;
  const recovery = await fs.readFile(await download.path(), 'utf8');
  const credentials = JSON.parse(recovery).credentials;
  testId = credentials[credentials.length - 1].id;
  await page.getByLabel('I confirm the timezone').check();
  await page.getByRole('button', { name: 'Encrypt and seal', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  await page.reload();
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  assert.equal(await overflow(), false);
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).click();
  await page.getByRole('dialog').waitFor();
  assert.equal(await overflow(), false);
  await page.getByLabel('Folder', { exact: true }).fill('Personal');
  await page.getByLabel('Tags, separated by commas').fill('future, note');
  await page.getByRole('button', { name: 'Save organization', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Folder and tags saved' }).waitFor();
  await page.getByRole('button', { name: 'Enable unlock reminder', exact: true }).click();
  await page.getByRole('button', { name: 'Remove unlock reminder', exact: true }).waitFor();
  assert.equal((await page.evaluate(() => window.__vaultNotifications)).length, 0);
  await page.getByText('Hand off access to this message', { exact: true }).click();
  await page.getByLabel('Handoff passphrase', { exact: true }).fill('browser-test-long-passphrase');
  await page.getByLabel('Confirm handoff passphrase', { exact: true }).fill('browser-test-long-passphrase');
  const handoffDownloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download encrypted handoff', exact: true }).click();
  const handoffFile = await fs.readFile(await (await handoffDownloaded).path(), 'utf8');
  assert.equal(handoffFile.includes(credentials[0].capability), false);
  // Device-clock advance affects informational text only; the API must deny.
  await page.evaluate(() => { window.originalNow = Date.now; Date.now = () => window.originalNow() + 999999999; });
  await page.getByRole('button', { name: 'Open message', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'has not authorized' }).waitFor();
  assert.equal(await page.locator('.plaintext-copy').count(), 0);
  await page.evaluate(() => { Date.now = window.originalNow; });
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  // Fixture-only deadline update makes the browser opening path immediate;
  // the separate API test exercises real elapsed time without updating a row.
  await pool.query('UPDATE vault_messages SET release_at=$1 WHERE id=$2', [Date.now() - 1000, testId]);
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await page.waitForFunction(() => window.__vaultNotifications.length === 1);
  assert.deepEqual(await page.evaluate(() => window.__vaultNotifications), [{ title: 'Vault release available', body: 'A message is ready. Open your vault to verify its release.' }]);
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).click();
  await page.getByRole('button', { name: 'Open message', exact: true }).click();
  await page.locator('.plaintext-copy').waitFor();
  assert.equal(await page.locator('.plaintext-copy').innerText(), note);
  await page.getByRole('button', { name: 'Close message', exact: true }).click();
  assert.equal(await page.locator('.plaintext-copy').count(), 0);
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.reload();
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  assert.equal((await page.evaluate(() => window.__vaultNotifications)).length, 0);
  const organizationControls = page.locator('.organization-filters select');
  await organizationControls.first().waitFor();
  await organizationControls.nth(0).selectOption('Personal');
  await organizationControls.nth(1).selectOption('future');
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  await organizationControls.nth(0).selectOption('__unfiled__');
  await page.getByRole('heading', { name: 'No matching messages' }).waitFor();
  await page.getByRole('button', { name: 'Reset search and filters' }).click();
  await page.getByLabel('Search titles or references').fill('not-a-matching-title');
  await page.getByRole('heading', { name: 'No matching messages' }).waitFor();
  await page.getByRole('button', { name: 'Reset search and filters' }).click();
  await page.getByRole('button', { name: 'Locked', exact: true }).click();
  await page.getByRole('heading', { name: 'No matching messages' }).waitFor();
  await page.getByRole('button', { name: 'Reset search and filters' }).click();
  await page.setViewportSize({ width: 375, height: 900 });
  assert.equal(await overflow(), false);
  assert.equal(await page.locator('h1').isVisible(), false);
  await page.getByRole('button').filter({ hasText: 'Browser verification note' }).click();
  assert.equal(await overflow(), false);
  await page.keyboard.press('Escape');
  const second = await browser.newContext({ viewport: { width: 375, height: 900 } });
  const recovered = await second.newPage();
  await recovered.goto(root);
  await recovered.getByRole('heading', { name: 'Create your first locked message' }).waitFor();
  await recovered.locator('input[type="file"]').setInputFiles({ name: 'recovery.json', mimeType: 'application/json', buffer: Buffer.from(recovery) });
  await recovered.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  const recipient = await browser.newContext({ viewport: { width: 375, height: 900 } });
  const recipientPage = await recipient.newPage();
  await recipientPage.goto(root);
  await recipientPage.getByRole('heading', { name: 'Create your first locked message' }).waitFor();
  await recipientPage.locator('input[type="file"]').setInputFiles({ name: 'handoff.json', mimeType: 'application/json', buffer: Buffer.from(handoffFile) });
  await recipientPage.getByRole('heading', { name: 'Import encrypted handoff', exact: true }).waitFor();
  await recipientPage.getByLabel('Handoff passphrase').fill('wrong-long-passphrase');
  await recipientPage.getByRole('button', { name: 'Decrypt and import access' }).click();
  await recipientPage.getByRole('alert').filter({ hasText: 'Incorrect passphrase' }).waitFor();
  await recipientPage.getByLabel('Handoff passphrase').fill('browser-test-long-passphrase');
  await recipientPage.getByRole('button', { name: 'Decrypt and import access' }).click();
  await recipientPage.getByRole('dialog').waitFor({ state: 'hidden' });
  await recipientPage.getByRole('button').filter({ hasText: 'Browser verification note' }).waitFor();
  assert.equal(await recipientPage.locator('.register-row').count(), 1);
  assert.equal(await recipientPage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  const bad = await browser.newContext(); const badPage = await bad.newPage();
  await badPage.goto(root);
  await badPage.getByRole('heading', { name: 'Create your first locked message' }).waitFor();
  await badPage.locator('input[type="file"]').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{bad}') });
  await badPage.getByRole('alert').filter({ hasText: 'Import failed' }).waitFor();
  assert.equal(await badPage.locator('.register-row').count(), 0);
  await badPage.route('**/api/vault/records/query', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Test API failure' }) }));
  await badPage.reload();
  await badPage.getByRole('heading', { name: 'Could not load your vault' }).waitFor();
  await badPage.unroute('**/api/vault/records/query');
  await badPage.getByRole('button', { name: 'Retry', exact: true }).click();
  await badPage.getByRole('heading', { name: 'Create your first locked message' }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: desktop/mobile no overflow; keyboard creation; encrypted reload persistence; advanced browser clock denied; local decryption; close clears plaintext; recovery into second browser; malformed import; filters/reset; API failure/retry; persistent folder/tags and filters; encrypted single-message handoff, wrong-passphrase denial and recipient restore; opted-in generic reminder only after API release and no repeats after reload. Notification rendering uses a browser-API test double, not proof of OS delivery.');
} finally {
  await browser.close();
  if (testId) await pool.query('DELETE FROM vault_messages WHERE id=$1', [testId]);
  await new Promise(resolve => server.close(resolve));
  await pool.end();
}
